// wiki Survivor:Artifacts 逐字英文描述（38 条，来自 wiki.gg 官方 wiki）
// primary = 主属性行；effect = 次要效果段（Milestone 之前）
module.exports = [
  { en: '5 Leaf Clover', rarity: 'Epic', primary: '+15 Luck, increases your Luck by +20 whenever you reroll anything (for 5 seconds).', effect: '' },
  { en: 'Ammo Rig', rarity: 'Epic', primary: '+50% Fire Rate, -15% Move Speed.', effect: '' },
  { en: 'Ancient Knowledge', rarity: 'Rare', primary: 'Gain 3 Levels', effect: '' },
  { en: 'Armor Grease', rarity: 'Rare', primary: '+5% Move Speed', effect: 'Increase your dodge by +2% while moving. Lasts for 3s, stacks up to 5 times.' },
  { en: 'Barley Bulb Juice', rarity: 'Rare', primary: 'Gain a temporary movespeed buff when standing still. Gives +5% Move Speed for 3 seconds. Stacks up to 5 times.', effect: '' },
  { en: 'BLT Ration Pack', rarity: 'Epic', primary: '+80 Max HP, +2 Life Regen.', effect: '' },
  { en: 'BRN Shield Belt', rarity: 'Rare', primary: '+ [FIRE] 15% Damage', effect: 'Explode in a ring of fire dealing damage and burning nearby enemies when you take damage. 15 seconds cooldown.' },
  { en: 'Chemist Kit', rarity: 'Rare', primary: '+15% Potency, +15% Status Effect Damage.', effect: '' },
  { en: 'Clipboard of Grudges', rarity: 'Rare', primary: '+10% XP Gain', effect: 'Gain XP when you take damage.' },
  { en: 'Company-issued Magnet', rarity: 'Rare', primary: '+10% XP Gain', effect: 'Spawns a magnet at the end of a stage that collects 50% of the XP.' },
  { en: 'Diver\'s Manual', rarity: 'Rare', primary: '+10% Damage, +10% Reload Speed, +5% Critical Chance, +15% Critical Damage.', effect: '' },
  { en: 'DRG Coupon', rarity: 'Rare', primary: 'Gives a 20% discount to all shop purchases.', effect: '' },
  { en: 'Energy Bars', rarity: 'Epic', primary: '+1% Damage, -3 Max HP for every player level.', effect: '' },
  { en: 'FRZ Shield Belt', rarity: 'Rare', primary: '+ [COLD] 15% Damage', effect: 'Knock back and slow nearby enemies when you take damage. 15 seconds cooldown.' },
  { en: 'Gold Scanner', rarity: 'Rare', primary: '', effect: 'You get a small chance to find Gold, when mining any kind of rock!' },
  { en: 'Gold-Tipped Bullets', rarity: 'Rare', primary: '', effect: 'Increase your damage done by 1% for every 5 Gold you have. Max 250 stacks.' },
  { en: 'Huuli Bait', rarity: 'Epic', primary: '', effect: 'Lure out a bunch of Huuli Hoarders - Gotta catch them all!' },
  { en: 'Jet Boots', rarity: 'Epic', primary: '', effect: 'Allows you to make a quick escape when taking damage. 20 seconds cooldown.' },
  { en: 'Multi Tool', rarity: 'Epic', primary: '', effect: '-25% Reload Speed, +5% Reload Speed for every unique [Tag] equipped.' },
  { en: 'Nitra Scanner', rarity: 'Rare', primary: '', effect: 'You get a small chance to find Nitra, when mining any kind of rock!' },
  { en: 'Nitragenic Powder', rarity: 'Rare', primary: '', effect: '+0.5% Critical Chance for every Nitra you have. Max 500 stacks.' },
  { en: 'Pay2Win Console', rarity: 'Epic', primary: '', effect: 'Increases your damage (+2.5%) whenever you reroll anything. Stacks up to 100 rerolls.' },
  { en: 'Pick Axtender', rarity: 'Epic', primary: '-10% Mining Speed', effect: 'Increases your reach when mining.' },
  { en: 'Pickled Nitra', rarity: 'Epic', primary: '', effect: 'Increases your damage (+2%) and decreases your move speed (-0.5%) for every Nitra you have.' },
  { en: 'Piercing Projectiles', rarity: 'Rare', primary: '+50% Piercing.', effect: '' },
  { en: 'Popup Tripod', rarity: 'Rare', primary: '', effect: 'Increase your fire rate (+2%) and reload speed (+2%) while standing still. Lasts for 3 seconds. Stacks up to 15 times.' },
  { en: 'Red Sugar Cube', rarity: 'Rare', primary: '', effect: 'Collecting Red Sugar increases your Max HP by 3' },
  { en: 'Reflex Calibrator', rarity: 'Rare', primary: '+5% Armor', effect: 'Increase your dodge chance when taking damage. +5% Dodge for 10 seconds. Stacks up to 5 times.' },
  { en: 'Salty Pretzel', rarity: 'Epic', primary: '+1 Armor for every 2% of missing HP.', effect: '' },
  { en: 'Squint-EE5', rarity: 'Epic', primary: '+30% Critical Chance, +100% Critical Damage, -30% Damage.', effect: '' },
  { en: 'Tactical Cookie', rarity: 'Rare', primary: '+5% Max HP', effect: 'Heals you for 50% of Max HP when entering the Drop Pod.' },
  { en: 'The MoCap', rarity: 'Epic', primary: '', effect: 'Increases your damage (+1%) for every (%) of missing HP.' },
  { en: 'Turbo Encabulator', rarity: 'Epic', primary: '', effect: '+3% Damage, +3% Reload Speed, -5% Mining Speed for every equipped Overclock.' },
  { en: 'Vita-miner Pills', rarity: 'Rare', primary: '+5% Max HP', effect: 'Increases the healing granted on level up.' },
  { en: 'Weapon Box', rarity: 'Epic', primary: '', effect: 'Equip an additional random level 6 weapon with a random overclock.' },
  { en: 'XP Scanner', rarity: 'Rare', primary: '', effect: 'You get a small chance to find XP, when mining any kind of rock!' },
];
